#!/bin/bash

# Variables
# $1 Mapa
# $2 Peso
# $3 Peso
# $4 Peso
# $5 Peso
# $6 Peso
# $7 Peso
# $8 Peso
# $9 Peso
# $10 fichero salida

java -jar tools/PlayGame-1.2.jar maps/map$1.txt 1000 1000 log.txt  2> "${10}" "java -jar MyBot.jar $2 $3 $4 $5 $6 $7 $8 $9  " "java -jar example_bots/DualBot.jar"
echo "Termino"

