#!/bin/bash

# Variables
# $1 Mapa
# $2 Peso
# $3 Peso
# $4 Peso
# $5 Peso
# $6 Peso
# $7 Peso
# $8 Peso
# $9 Peso
# $10 fichero salida

#java -jar ../../tools/PlayGame-1.2.jar ../../maps/4/map$1.txt 10000 500 log.txt  2> "${10}" "java -jar ../../MyBot/dist/MyBot.jar ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9}  " "java -jar ../../MyBot/dist/MyBot.jar ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18}"  "java -jar ../../example_bots/DualBot.jar" "java -jar ../../example_bots/DualBot.jar" ; perl analiza.pl ${10} > ${10}"_res"
#java -jar ../../tools/PlayGame-1.2.jar ../../maps/4/map$1.txt 10000 500 log.txt  2> "${10}" "java -jar ../../MyBot/dist/MyBot.jar ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9}  " "java -jar ../../MyBot/dist/MyBot.jar ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18}"  "java -jar ../../MyBot/dist/MyBotEje8.jar" "java -jar ../../MyBot/dist/MyBotEje8.jar" ; perl analiza.pl ${10} > ${10}"_res"
java -jar ../../tools/PlayGame-1.2.jar ../../maps/4/map$1.txt 10000 500 log.txt  2> "${10}" "java -jar ../../MyBot/dist/MyBot.jar ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9}  " "java -jar ../../MyBot/dist/MyBotEje8.jar"  "java -jar ../../MyBot/dist/MyBotEje8.jar" "java -jar ../../MyBot/dist/MyBotEje8.jar" ; perl analiza.pl ${10} > ${10}"_res"


